# Generated by Django 3.1.7 on 2021-09-14 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Shop', '0008_auto_20210913_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=200)),
                ('image', models.ImageField(upload_to='media/images/Item/')),
                ('is_published', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('expiry_date', models.DateTimeField(default=False)),
                ('is_stocked', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Item.itemcategory')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.shop')),
            ],
        ),
    ]
