# Generated by Django 3.1.7 on 2021-09-14 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Item', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_category',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ManyToManyField(default=True, related_name='item_category', to='Item.ItemCategory'),
        ),
        migrations.AddField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='created_by',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_cat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='expiry_date',
            field=models.DateTimeField(default=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_stocked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
