# Generated by Django 3.1.7 on 2021-09-13 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_auto_20210913_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcategory',
            name='is_active',
        ),
    ]
