# Generated by Django 3.1.7 on 2021-08-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20210729_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassword',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
