# Generated by Django 3.2.5 on 2021-08-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20210801_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaluser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='ResetPassword',
        ),
    ]
