# Generated by Django 3.1.7 on 2021-09-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20210824_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaluser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
