# Generated by Django 3.1.7 on 2021-09-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20210909_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaluser',
            name='image',
            field=models.ImageField(default=None, upload_to='media/images/user/'),
        ),
    ]
